### ISSUE TITLE
Example 2 - Chrome/Edge fires video streaming expressjs route twice, firefox only once

### ISSUE THREAD

**Issue by jpollard-github** [bootstrapping-microservices/chapter-5#13]
Mr. Davis, any idea why in Example 2, viewing the http://localhost:4001/video route on Chrome/Edge causes the route to be called twice, while on Firefox only once?

**Comment by gorangatuzo** [comment]
Noticed the same thing but saw that it's already explained [here](https://github.com/bootstrapping-microservices/chapter-5/issues/8)

**Comment by jpollard-github** [comment]
Cool, thank you!
